name: docker-build-test

on:
  push:
   branches: [master]

  workflow_dispatch:
    
jobs:
  build:
   runs-on: ubuntu-latest

   steps:
    - name: Checkout repo code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Build image only
      uses: docker/build-push-action@v3
      with:
       push: false
       tags: aaanh/minecraft:ci-build-test